### PR TITLE
Swift3 for Jedi

### PR DESCRIPTION
**Pull request by corinnekrych**
WIP for @jcesarmobile to look at

### CODE REVIEW

**Comment by corinnekrych** [comment]
This is the update of all demo with released line AGIOS-535

**Comment by jcesarmobile** [comment]
👀

**Comment by jcesarmobile** [comment]
I've send some changes
https://github.com/corinnekrych/aerogear-ios-cookbook-1/pull/10

On Shoot I couldn't make facebook share work, google and keycloack worded fine, not sure if the problem is on the example or on the oauth library
Should we make Howdy use CocoaPods?

**Comment by jcesarmobile** [comment]
LGTM

**Pull request merged**
