### PR TITLE
Shoot is Swift2.3

### PR DESCRIPTION
**Pull request by corinnekrych**
Migrate to Swift2.3 (using Xcode8 migrator)
Project can be opened in Xcode 7.3.1 or Xcode8 and ran on iOS10

### CODE REVIEW

**Comment by danielpassos** [comment]
| Feature      | Status                           |
|------------|-----------------------|
| XCode 7.3  | :heavy_check_mark:    |
| XCode 8.0 |  Waiting for download |
| iOS 10        |  Installing                     |

**Comment by danielpassos** [comment]
# XCode 8.0

## When open

screenshot 2016-09-21 18 56 35
I have clicked in _later_

screenshot 2016-09-21 18 56 05
I have clicked in _later_

## When try to build

``` 
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
```
## After convert to _Swift 3_

screenshot 2016-09-21 19 01 31

screenshot 2016-09-21 19 02 58


@corinnekrych Convert screens are something expected?

**Comment by corinnekrych** [comment]
@danielpassos Good catch I forgot to check-in the CocoaPoads workaround in Podfile.

The issue is located in the generated Pods for the aerogear-ios-http/oauth2, see:
unspecified-9
This is a known issue with CocoaPods 1.0.1 (it is fixed in 1.1.0.beta.1).
With the addition in Podile, you will not be prompted again.
🌹 Thanks!

**Comment by jcesarmobile** [comment]
Builds and works fine on both Xcode 7.3.1 and Xcode 8 now

**Pull request merged**
