### PR TITLE
Consistency for application secret

### PR DESCRIPTION
**Pull request by abstractj**
I don't think its necessary to expose personal application ID.

The goal of this PR is to keep the consistency across our examples: https://github.com/aerogear/aerogear-cordova-cookbook/pull/11

### CODE REVIEW

**Comment by corinnekrych** [comment]
@abstractj this is not secret it's the client id, it public 
the good part of having it is that dev can test shoot app with 0 config.
I'd rather keep tbh

**Comment by abstractj** [comment]
@corinnekrych sorry, bad wording. What happens if you mistakenly delete that? The app just stop to work, right?

**Comment by abstractj** [comment]
@cvasilak @danielpassos @sebastienblanc @lfryc would you mind to review?

**Comment by cvasilak** [comment]
I would say since other cookbooks follow the same pattern of empty id's, we can do the same here. Possible publishing the app on the App Store and have these id's contained in-there can be a solution.

@abstractj opened a small https://github.com/abstractj/aerogear-ios-cookbook/pull/1 against it removing a note on the readme.md

**Comment by danielpassos** [comment]
After merge @cvasilak  :+1:

**Comment by abstractj** [comment]
@danielpassos @cvasilak done, thank you

**Comment by danielpassos** [comment]
Landed at https://github.com/aerogear/aerogear-ios-cookbook/commit/5c969395b32588c41a25b8c05668c2afad09fce2

**Pull request closed without merging**
