### PR TITLE
Add WebView instruction for Shoot

### PR DESCRIPTION
**Pull request by corinnekrych**
@cvasilak mind a review
To test:
1. change Podfile to point to:
pod 'AeroGearOAuth2', :git => 'https://github.com/corinnekrych/aerogear-ios-oauth2-1', :branch => 'AGIOS-414.webview'
2. uncomment line 38 as explained in README

### CODE REVIEW

**Comment by cvasilak** [comment]
:eyes: looking at

**Comment by cvasilak** [comment]
noticed that if 2-factor is enabled on the sites, the web view controller:
- for google goes to home page of search results.
- facebook remains in a white-screen

The end effect is that the popup controller doesn't dismiss.

Note that I have disabled fb temporally and works correctly so something in 2-factor is blocking it.

**Comment by corinnekrych** [comment]
Mmmm... wierd I can't reproduce the issue with 2 factors auth.
See attached gif
shoot_webview

I fixed the rotating issue with webview.

**Comment by danielpassos** [comment]
:eyes:

**Comment by danielpassos** [comment]
Hey @corinnekrych I got the same problem of @cvasilak, I have a 2-factor enable and got the white-screen

Here is my screen flow:

|   |   |
|---|---|
|  |  
|  |  
|  |

The App output (NSLog):

```
2015-03-30 20:18:12.469 Shoot[230:25927] Presenting view controllers on detached view controllers is discouraged <Shoot.ViewController: 0x17e4b780>.
2015-03-30 20:18:12.819 Shoot[230:25927] Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates.
2015-03-30 20:18:13.381 Shoot[230:25927] Unbalanced calls to begin/end appearance transitions for <UINavigationController: 0x17d42b90>.
Perform photo upload with Facebook
AccessToken not found
RefreshToken not found
2015-03-30 20:18:52.946 Shoot[230:25927] Can't find keyplane that supports type 5 for keyboard iPhone-Portrait-PhonePad; using 2870935746_Portrait_iPhone-Complex-Pad_Default
```

**Comment by corinnekrych** [comment]
:eyes:
Looking at fb
Thanks @danielpassos

**Comment by corinnekrych** [comment]
@danielpassos in AppDelegate.swift, just before return true if you add:
 UIApplication.sharedApplication().keyWindow?.rootViewController?.dismissViewControllerAnimated(true, nil)
then the flow is ok I guess?

**Comment by danielpassos** [comment]
Let me try!

**Comment by cvasilak** [comment]
from my tests:
I have retested,  its the deployment on the actual device that fails on the webview approach, Google redirectes to the search page FB gives the white page. External browser works fine in the device.

Both work though, external and webview in the simulator.

**Comment by danielpassos** [comment]
After clean up my device and the keychain, I tested it again

| -                            | Facebook | Google | KeyCloak     |
|:----------------------------:|:--------:|:------:|:------------:|
| Device + Browser + 2-Factor  | :+1:     | :+1:   | _NOT TESTED_ |
| Device + WebView + 2-Factor  | :+1:     | :+1:   | _NOT TESTED_ |

**Comment by corinnekrych** [comment]
@cvasilak I can reproduce the white screen issue on fb with 2-factor on real device. Let me dig that one further. But Google 2factor on device is working fine.
The issues is related to async flow somehow.
:eyes:

**Comment by matzew** [comment]
@corinnekrych @cvasilak is this ready?

**Comment by corinnekrych** [comment]
linked to https://github.com/aerogear/aerogear-ios-oauth2/pull/25

**Pull request merged**
