### PR TITLE
Remove product quickstarts

### PR DESCRIPTION
**Pull request by matzew**
remvoing quickstart submodules and updating readme

### CODE REVIEW

**Comment by matzew** [comment]
@corinnekrych @abstractj mind to review ?

**Comment by matzew** [comment]
Similar to Android, I added a table to link to other (non community demos)

**Comment by danielpassos** [comment]
:+1:

**Comment by corinnekrych** [comment]
+1

**Comment by cvasilak** [comment]
+1

(can merge tomorrow morning)

**Comment by danielpassos** [comment]
Landed at https://github.com/aerogear/aerogear-ios-cookbook/commit/891ddfd43292268c667e9c9e8407ee3646e2709f

**Pull request closed without merging**
