### PR TITLE
RHMAP-10094 updated Jedi project to Swift 2.3

### PR DESCRIPTION
**Pull request by jcesarmobile**

### CODE REVIEW

**Comment by jcesarmobile** [comment]
@corinnekrych can you review?

**Comment by corinnekrych** [comment]
@jcesarmobile small suggestion here: https://github.com/jcesarmobile/aerogear-ios-cookbook/pull/1
+1 to merge, it works great

**Comment by jcesarmobile** [comment]
merged your PR

**Comment by jcesarmobile** [comment]
forgot to commit the README.md

**Pull request merged**
