### PR TITLE
Agios 490.cocoapods.1.x

### PR DESCRIPTION
**Pull request by corinnekrych**

### CODE REVIEW

**Comment by matzew** [comment]
@corinnekrych will the relevant iOS apps in here:
https://github.com/jboss-mobile/unified-push-helloworld

also being updated w/ CocoaPods 1.0x syntax ?

**Comment by corinnekrych** [comment]
@matzew Good point, yes!
let me add them to AGIOS-490

**Comment by jcesarmobile** [comment]
Authentication/README.md, ChuckNorrisJokes/README.md, SharedShoot/README.md, Shoot/README.md and Weather/README.md have some references to cocoapods instead of CocoaPods. It also says that iOS7 is supported, but the Podfile has iOS 8. 

The deployment target for the Authentication project is 9.3

Two-Factor/README.md has cocoapods instead of CocoaPods, and refers to version 0.36. It says it supports iOS7, but the Podfile and deployment target are set to iOS8

**Comment by corinnekrych** [comment]
@jcesarmobile thanks for the catch. ok to merge?

**Comment by jcesarmobile** [comment]
The deployment target for the Authentication project is still 9.3

**Comment by corinnekrych** [comment]
@jcesarmobile Ahhh Good catch
💯

**Comment by jcesarmobile** [comment]
LGTM

**Pull request merged**
