### PR TITLE
RHMAP-10113 Update to Swift 3.0

### PR DESCRIPTION
**Pull request by jcesarmobile**

### CODE REVIEW

**Comment by jcesarmobile** [comment]
@corinnekrych can you review?
Manual changes I made
https://github.com/aerogear/aerogear-ios-cookbook/pull/103/files#diff-f6b3467018e3e53855bb608f8774e610R41
https://github.com/aerogear/aerogear-ios-cookbook/pull/103/files#diff-a85355bf0c33d867df1bae38cb842fa6R66
https://github.com/aerogear/aerogear-ios-cookbook/pull/103/files#diff-a85355bf0c33d867df1bae38cb842fa6R67

**Comment by corinnekrych** [comment]
👀

**Comment by corinnekrych** [comment]
+1

**Comment by corinnekrych** [comment]
@jcesarmobile could you update to master branch:

**Comment by jcesarmobile** [comment]
@corinnekrych done!

**Pull request merged**
