### PR TITLE
Agios 384.diffmatchpatch.jedi.demo

### PR DESCRIPTION
**Pull request by corinnekrych**
Make Jedi demo work for DiffMatchPatch
@cvasilak would you mind reviewing it?

### CODE REVIEW

**Comment by cvasilak** [comment]
tested with the  [Android demo](https://github.com/danbev/android-diffsync-demo/tree/diffmatchpatch-sync-server-example) and worked great :+1: 

opened a [PR](https://github.com/corinnekrych/aerogear-ios-cookbook-1/pull/8) against it with a small change on an extra field and some readme polish.

**Comment by cvasilak** [comment]
@danbev mind to have a look also?

**Comment by danbev** [comment]
@cvasilak Sure thing. Will take a look now.

**Comment by danbev** [comment]
@corinnekrych Can you merge @cvasilak PR and I'll take a look as those changes are required.

**Comment by danbev** [comment]
:+1: Only if https://github.com/corinnekrych/aerogear-ios-cookbook-1/pull/8 is merged first.

**Comment by corinnekrych** [comment]
Thanks @cvasilak I merged your PR, testing android version is useful indeed!
about to merge

**Pull request merged**
