### PR TITLE
AEROGEAR-1646 Update the readme file from the cookbooks with the repositories recently moved

### PR DESCRIPTION
**Pull request by abstractj**

### CODE REVIEW

**Comment by matzew** [comment]
+1

**Comment by corinnekrych** [comment]
@abstractj @matzew Actually this PR should go against 1.6.x branch which contain README with AeroDoc.
AeroDoc was not moved to master as it's not yet migrated with 2.0 libs.

**Comment by abstractj** [comment]
Hold on, fixing in a bit

**Comment by abstractj** [comment]
@matzew @corinnekrych like requested, updated here https://github.com/aerogear/aerogear-ios-cookbook/pull/68

**Pull request closed without merging**
