### PR TITLE
AGIOS-380: Removal of Keycloak URL from settings at the cookbooks

### PR DESCRIPTION
**Pull request by abstractj**

### CODE REVIEW

**Comment by cvasilak** [comment]
tested and worked great :+1: 

I am +1 on removing the keyckoak url from settings and work against the deployed openshift instance out-of-the-box. If the user decides the doc specifies the url to change and where.

@corinnekrych wdyth?

**Comment by corinnekrych** [comment]
@abstractj Given that we don't want to maintain the openshift instance, I would default to localhost:8080
That way if the shoot app is run on ios simulator and keycloak deployed locally it will work out of the box.

+1 for keeping clear keychain settings, this is important

**Comment by abstractj** [comment]
@corinnekrych @cvasilak updated, let me know if something is wrong

**Comment by cvasilak** [comment]
thank you @abstractj :rocket: landed on https://github.com/aerogear/aerogear-ios-cookbook/commit/d7d661f500f2c572c06da2e577d104874b7dbcc1

**Pull request merged**
